### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by gonzalofh** [SofSanUrb/TicTacToe#6]
Create a more standard project layout for your Python repo.
You can follow guides like this: https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/
By now, your project is simple enough so don't spend too much time in things like dependency management.
Most important thing for now: give your project a version number. In the guide you'll find how.
And here's some other documentation about how to understand semantic versioning: https://semver.org/

**Comment by sofisdev** [comment]
Tag 1.0.0. was created
Packaging will be taken into account

**Comment by sofisdev** [comment]
Issue is closed
